# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    TOP_DOMAIN: '%env(TOP_DOMAIN)%'
    APP_ENV: '%env(APP_ENV)%'
    # SHARED_FOLDER: '%env(SHARED_FOLDER)%'
    CHROME_BINARY: '%env(CHROME_BINARY)%'
    MASTER_API_URL: '%env(MASTER_API_URL)%'
    COMPARATOR_URL: '%env(COMPARATOR_URL)%'
    COMPARATOR_PUBLIC_URL: '%env(COMPARATOR_PUBLIC_URL)%'
    AUTH_API_URL: '%env(AUTH_API_URL)%'
    ADMIN_API_URL: '%env(ADMIN_API_URL)%'
    CHAT_API_URL: '%env(CHAT_API_URL)%'
    CORE_API_URL: '%env(CORE_API_URL)%'
    SERVICE_API_KEY: '%env(SERVICE_API_KEY)%'
    CORS_ALLOW_ORIGIN: '%env(CORS_ALLOW_ORIGIN)%'
    SHORTENER_API_URL: '%env(SHORTENER_API_URL)%'
    SELL_API_URL: '%env(SELL_API_URL)%'

    SERVICE_PREFIX: '%env(SERVICE_PREFIX)%'
    SERVICE_SUFFIX: '%env(SERVICE_SUFFIX)%'

    # File upload directory
    upload_folder: '%kernel.project_dir%/public/uploads'
    
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'


    App\Security\MasterAuthenticator:
        parent: lexik_jwt_authentication.security.jwt_authenticator

    # App\Listeners\PopupExceptionHandler:
    #     tags:
    #         - {name: kernel.event_listener, event: kernel.exception, method: onKernelException}

    App\Listeners\UserEvent:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: postPersist}
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: preRemove }
            - { name: doctrine.event_listener, event: preFlush }
            - { name: doctrine.event_listener, event: postFlush }
            - { name: doctrine.event_listener, event: preRemove }
            
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Security\Voter\UserVoter:
        public: false
        arguments: ['@security.role_hierarchy']

    App\Command\GeneratePostmanCollectionCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Controller\StripeWebhookController:
        arguments:
            $stripeWebhookSecret: '%env(STRIPE_WEBHOOK_SECRET)%'

    App\Service\StripeService:
        arguments:
            $stripeSecretKey: '%env(STRIPE_SECRET_KEY)%'

    App\Service\FileService:
        arguments:
            $uploadFolder: '%upload_folder%'
